Implement UI changes/fixes requested by RCI
pacificclimate/climate-explorer-frontend pull request #465
Opened 2024-06-03 19:59 UTC by eyvorchuk

This PR contains the UI changes/fixes RCI requested while experimenting with the MBCn climatologies page. These are the changes:

- Replaces instances of `Yearly` with `Annual`
- Represents the `PCIC12` dataset with a thick black line in the `Model Context` graph regardless of the selected model
- Shows the graph tooltip for the selected model in the `Model Context` graph.
- Instead of using exact dates in the x-axis labels of the `Long Term Average` and `Model Context` graphs, they use decadal periods (e.g. `2020s` instead of `2025-07-02`). This is because for some periods (like 1981-2010), some models have `1996-07-02` as their middle date while others have `1997-07-02`, causing the dates to overlap in the `Model Context` graph. This change ensures that the label is the same for all models in each period.
- Removes `Snapshot` graph since the information is already in the `Model Context` graph
- In the `Filtered Datasets Summary` and `Data Map`, only includes the `run_id` if the selected model has multiple runs (e.g. MIROC5 has `r1i1p1` and `r3i1p1`)
- Enables the historical baseline in the `Change from Baseline` graph to be selectable by the dropdown, using 1981-2010 as the default (also resolves #343)

Demo available at https://services.pacificclimate.org/dev/pcex/app/#/data/climo/ce_files

2024-06-06 21:51 UTC, rod-glover requested changes
Looking quite good. Some comments inline, and the following two questions:

1. 
> Enables the historical baseline in the Change from Baseline graph to be selectable by the dropdown

Can you provide an example case where this dropdown appears? I don't see it in any of the cases I pulled up.

2.
> In the Filtered Datasets Summary and Data Map, only includes the run_id if the selected model has multiple runs (e.g. MIROC5 has r1i1p1 and r3i1p1)

I don't see any difference in the label or the content for Filtered Datasets Summary. `run_id` is included/excluded with MIROC5/PCIC12 respectively in Data Map, but not in Filtered Datasets Summary.

2024-06-06 21:51 UTC, rod-glover commented on src/components/DataSpecSelector/DataSpecSelector.js
> +    );
It looks like `ids = _.sortedUniqBy(...` is duplicated. Is that intended?

2024-06-06 21:51 UTC, rod-glover commented on src/components/DataSpecSelector/DataSpecSelector.js
> +    if (ids[0][1].split(" ")[0] == ids[ids.length - 1][1].split(" ")[0]) {
Never use `==` comparison; its type-coercion is too tricky and leads to errors. Use only strict equality `===`. This is standard advice in JS land.

2024-06-06 21:51 UTC, rod-glover commented on src/components/DataSpecSelector/DataSpecSelector.js
> +    if (ids[0][1].split(" ")[0] == ids[ids.length - 1][1].split(" ")[0]) {
Also, it's hard to deduce what is being compared here and why. Suggest you decompose the `ids` items into helpfully-named values that you then compare. Something like

```
const first_run_id = ids[0][1].split(" ")[0];
const last_run_id = ids[ids.length - 1][1].split(" ")[0];
if (first_run_id === last_run_id) {
   ...
```

If you were feeling really fun you could define a temp function `const run_id = id = id[1].split(" ")[0]` to DRY things up.

2024-06-06 21:51 UTC, rod-glover commented on src/components/DataSpecSelector/DataSpecSelector.js
> +    if (ids[0][1].split(" ")[0] == ids[ids.length - 1][1].split(" ")[0]) {
Alternatively, could the condition be evaluated by 

```
import { hasMultiRuns } from "../../map-controllers/map-helpers";
```

as it is in another component further down?

2024-06-06 21:51 UTC, rod-glover commented on src/components/data-presentation/FilteredDatasetsSummary/FilteredDatasetsSummary.js
> +    }
Much duplication here. DRY up using a function.

2024-06-10 20:31 UTC, eyvorchuk commented
@rod-glover 
> Can you provide an example case where this dropdown appears? I don't see it in any of the cases I pulled up.

Could we meet to see what you're looking at? I just opened the [demo](https://services.pacificclimate.org/dev/pcex/app/#/data/climo/ce_files) and I was able to see the dropdown in the `Change From Baseline` graph.
> I don't see any difference in the label or the content for Filtered Datasets Summary. `run_id` is included/excluded with MIROC5/PCIC12 respectively in Data Map, but not in Filtered Datasets Summary.

Sorry, I should've worded this better for the `Filtered Datasets Summary`. Only the `Label in Selectors` column excludes the `run_id` in cases where a model has only one run. Currently in production, for PCIC12 from 1971-2000 as an example, that column displays the label as `rXi1p1 1971-2000`, but with this change, the label will be `1971-2000` instead.

2024-06-10 21:50 UTC, rod-glover commented
> @rod-glover
> 
> > Can you provide an example case where this dropdown appears? I don't see it in any of the cases I pulled up.
> 
> Could we meet to see what you're looking at? I just opened the [demo](https://services.pacificclimate.org/dev/pcex/app/#/data/climo/ce_files) and I was able to see the dropdown in the `Change From Baseline` graph.

I see now that the "Dataset" dropdown is what we're talking about. I misinterpreted it and thought it chose which future dataset (or something) would be displayed. For an inexpert (or inattentive) user, I think a better label here would be "Baseline".

> 
> > I don't see any difference in the label or the content for Filtered Datasets Summary. `run_id` is included/excluded with MIROC5/PCIC12 respectively in Data Map, but not in Filtered Datasets Summary.
> 
> Sorry, I should've worded this better for the `Filtered Datasets Summary`. Only the `Label in Selectors` column excludes the `run_id` in cases where a model has only one run. Currently in production, for PCIC12 from 1971-2000 as an example, that column displays the label as `rXi1p1 1971-2000`, but with this change, the label will be `1971-2000` instead.

Ah, understood now.

2024-06-11 19:24 UTC, rod-glover approved these changes
I see you have changed the label in code from "Dataset" to "Baseline", although it doesn't seem to have been deployed yet. I'll trust it all works! Nice work.

2024-06-11 20:01 UTC, merged